### PR TITLE
Return partial guild object in use_invite

### PR DESCRIPTION
**Pull request by jay3332**

### CODE REVIEW

**Comment by tazz4843** [comment]
if it builds it looks good to me

**Review by Cryptex-github — DISMISSED** [review]
It looks Ferris as long as it builds!!!

**Comment by randomairborne** [comment]
Fix clippy please. Sqlx is fine, but clippy should pass.

**Comment by hydrostaticcog** [comment]
This PR is being frozen until the webserver crate has been ported to axum. The problem here might be resolved in that rewrite, so this will stay open for now in order to convey updates.

**Comment by hydrostaticcog** [comment]
Needs to be updated from upstream and rewritten for rewrite

**Pull request closed without merging**
