### PR TITLE
prefer .expect instead of unwrapping into a panic

### PR DESCRIPTION
**Pull request by jay3332**
Additionally run the sqlx::migrate macro with no arguments since it defaults to `../migrations` (which is what it was before)

### CODE REVIEW

**Comment by randomairborne** [comment]
Please fix the checks.

**Comment by jay3332** [comment]
> Please fix the checks.

neither of them seem very fixable to me/related as a result of this PR, potentially a seperate PR could be created to fix these checks. with this project not having been touched in a long time im pretty sure many are related to breaking changes (since the server uses nightly.) 

one example is `SyncOnceCell` which was renamed to `OnceLock`

**Comment by randomairborne** [comment]
They’re still worth fixing.

**Review by randomairborne — DISMISSED** [review]

**Comment by hydrostaticcog** [comment]
Since the checks originate in an area of the code that is not being changed here, I think it is fine. I am approving, but I do want to wait for @tazz4843 to merge.

**Comment by hydrostaticcog** [comment]
I take it back, this needs to go onto the dev branch to avoid conflicts down the line.

**Review by hydrostaticcog — CHANGES_REQUESTED** [review]
Target `develop` branch

**Comment by jay3332** [comment]
> Target `develop` branch

just a heads up, develop is 9 commits behind master although im sure you can just merge

**Comment by jay3332** [comment]
commit is now targeted to develop

**Comment by hydrostaticcog** [comment]
The missing commits appear to be merge commits, so I am not concerned. Approving now.

**Review by hydrostaticcog — APPROVED** [review]

**Pull request merged**
